-- Initial schema for Physio Manager (V0) - PostgreSQL
-- Creates core tables: pacientes, servicos_config, assinaturas, atendimentos, cobrancas_mensais, usuarios

CREATE TABLE IF NOT EXISTS pacientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_nascimento DATE,
    cpf VARCHAR(11) UNIQUE,
    telefone VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado VARCHAR(20),
    cep VARCHAR(8),
    complemento VARCHAR(100),
    data_cadastro TIMESTAMP,
    anamnese TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS servicos_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    valor_base NUMERIC(10,2) NOT NULL,
    pct_clinica NUMERIC(5,2) NOT NULL,
    pct_profissional NUMERIC(5,2) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS assinaturas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    servico_id INTEGER NOT NULL,
    valor_mensal NUMERIC(10,2) NOT NULL,
    dia_vencimento INTEGER NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_inicio DATE NOT NULL,
    data_cancelamento TIMESTAMP,
    CONSTRAINT fk_assinatura_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
    CONSTRAINT fk_assinatura_servico FOREIGN KEY (servico_id) REFERENCES servicos_config(id)
);

CREATE TABLE IF NOT EXISTS atendimentos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    servico_base_id INTEGER NOT NULL,
    data_hora_inicio TIMESTAMP NOT NULL,
    valor_cobrado NUMERIC(10,2) NOT NULL,
    pct_clinica_snapshot NUMERIC(5,2) NOT NULL,
    pct_profissional_snapshot NUMERIC(5,2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    data_hora_fim TIMESTAMP,
    evolucao TEXT,
    recebedor VARCHAR(20),
    tipo_pagamento VARCHAR(25),
    CONSTRAINT fk_atendimento_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
    CONSTRAINT fk_atendimento_servico FOREIGN KEY (servico_base_id) REFERENCES servicos_config(id)
);

CREATE TABLE IF NOT EXISTS cobrancas_mensais (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assinatura_id INTEGER NOT NULL,
    mes_referencia INTEGER NOT NULL,
    ano_referencia INTEGER NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    data_pagamento DATE,
    recebedor VARCHAR(20),
    tipo_pagamento VARCHAR(25),
    pct_clinica_snapshot NUMERIC(5,2) NOT NULL,
    pct_profissional_snapshot NUMERIC(5,2) NOT NULL,
    CONSTRAINT fk_cobranca_assinatura FOREIGN KEY (assinatura_id) REFERENCES assinaturas(id)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255),
    senha VARCHAR(255),
    role VARCHAR(100)
);

-- Indexes to improve common queries
CREATE INDEX IF NOT EXISTS idx_atendimentos_paciente ON atendimentos (paciente_id);
CREATE INDEX IF NOT EXISTS idx_assinaturas_paciente ON assinaturas (paciente_id);
CREATE INDEX IF NOT EXISTS idx_cobrancas_assinatura ON cobrancas_mensais (assinatura_id);
